name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_and_deploy_job:
    runs-on: self-hosted
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0

      - name: Install wasm-tools
        run: dotnet workload install wasm-tools wasm-experimental

      - name: Install DotNetCompress
        run: dotnet tool install --global DotNetCompress --version 1.0.0-preview.4 --no-cache

      - name: Publish .NET Project
        run: dotnet publish src/XamlPlayground.Wasm/XamlPlayground.Wasm.csproj -c Release -o release --nologo

      - name: Brotli Compress Output (dll)
        run: DotNetCompress -d src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/managed -p '*.dll'

      - name: Brotli Compress Output (js)
        run: DotNetCompress -d src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/ -p '*.js'

      - name: Brotli Compress Output (wasm)
        run: DotNetCompress -d src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/ -p '*.wasm'

      - name: copy index.html to 404.html
        run: cp src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/index.html src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/404.html
        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_DESERT_014E22103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Modify this to where your SSG places the built HTML - could be `dist`, `build`... check your config          
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
