name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0

    - name: Install wasm-tools
      run: dotnet workload install wasm-tools wasm-experimental

    - name: Publish .NET Project
      run: dotnet publish src/XamlPlayground.Wasm/XamlPlayground.Wasm.csproj -c Release -o release --nologo

    - name: Change base-tag in index.html from / to XamlPlayground
      run: sed -i 's/<base href="\/" \/>/<base href="\/XamlPlayground\/" \/>/g' src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/index.html

    - name: copy index.html to 404.html
      run: cp src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/index.html src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/404.html

    - name: Add .nojekyll file
      run: touch src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: src/XamlPlayground.Wasm/bin/Release/net7.0/browser-wasm/AppBundle
